[theme]
primaryColor = "#00ff00"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false
